version: "3"

services:
  app:
    image: node:20.14.0@sha256:693bbbae84341aaf732ebafc141ba7a142c7e19070ead565db67d5b4c223a633
    ports:
      - 4321:4321
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0
    volumes:
      - ./:/app
