# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  db:
    image: postgres:17@sha256:f176fef320ed02c347e9f85352620945547a9a23038f02b57cf7939a198182ae
    restart: always
    container_name: integration-tests-prisma
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: integration-tests-api
    ports:
      - '8898:8888'
